# Site Settings
title: How Dare You Review | Movies
email: saul.zach@gmail.com
description: Opinions about films from casual observers who have no right to hold Opinions. 
baseurl: "/howdareyoureview" # the subpath of your site, e.g. /blog
url: "https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Zach Saul
user_description: Writer, Designer, Movie Lover. 
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
